### ISSUE TITLE
Roadmap update

### ISSUE THREAD

**Issue by betacar** [moleculer-ruby/moleculer#67]
Hi!
This more of a question than a bug or issue. 

I would like to invest more time contributing to this project, but don't know where to continue. I noticed the roadmap on the README file, but wanted to confirm is accurate and check if anyone is working on any of the 0.2 features.

Also, wanted to know if you're planning to mirror MoleculerJS' features 1-1, or this project will take liberties and maybe diverge a bit on its offers.

:)

**Comment by fugufish** [comment]
@betacar thanks for reaching out! Let me talk to my team but I think we would be more than happy for the help. As for 1-1, I am open to adding additional features not found in Moleculer itself but we want maintain full compatibility with MoleculerJS as we use it for polyglot integration.

**Comment by fugufish** [comment]
closed, roadmap updated. @betacar check your email

**Comment by betacar** [comment]
Received and accepted. Thank you @fugufish!
